language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - gcovr
      
before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel_3.4.1-linux-x86_64.deb
  - sudo dpkg -i bazel_3.4.1-linux-x86_64.deb

script:
  - bazel test //tests:tests
#  - bazel build //cicflowmeter-c:cicflowmeter
#  - bazel test //cicflowmeter-c:cicflowmeter
#  - bazel coverage //cicflowmeter-c:cicflowmeter

after_success:
#  - cat bazel-testlogs/cicflowmeter-c/cicflowmeter/baseline_coverage.dat
  - bash <(curl -s https://codecov.io/bash)
